# Dockerfile has three Arguments: base, tag, branch
#
# To build the image:
# $ docker build -t o3sources .  # if not built already
# $ docker build -t <name> -f Dockerfile.tco3_zm .
FROM o3sources:latest
ENTRYPOINT ["/app/scripts/tco3_zm.py"]
