CCMI-1_ACCESS_ACCESS-CCM-refC2:
  operations:
  - lon_mean
  source: CCMI-1
  tco3_zm:
    paths: CCMI-1_ACCESS_ACCESS-CCM-refC2/*.nc
    variable: equivalent_thickness_at_stp_of_atmosphere_ozone_content 
    plot_color: purple
    plot_linestyle: solid
    plot_marker: o
  vmro3_zm:
    paths: CCMI-1_ACCESS_ACCESS-CCM-refC2/*.nc
    variable: vmro3
    plot_color: darkblue
    plot_linestyle: solid
    plot_marker: '*'
CCMI-1_ACCESS_ACCESS-CCM-senC2fGHG:
  operations:
  - lon_mean
  source: CCMI-1
  tco3_zm:
    paths: CCMI-1_ACCESS_ACCESS-CCM-senC2fGHG/*.nc
    variable: equivalent_thickness_at_stp_of_atmosphere_ozone_content
    plot_color: brown
    plot_linestyle: solid
    plot_marker: o
CCMI-1_CESM1-CAM4Chem-refC1_r1i1p1:
  operations:
  - lon_mean
  source: CCMI-1
  tco3_zm:
    paths: CCMI-1_CESM1-CAM4Chem-refC1_r1i1p1/*.nc
    variable: equivalent_thickness_at_stp_of_atmosphere_ozone_content
    plot_color: green
    plot_linestyle: solid
    plot_marker: o

